services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: npm run dev

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    command: npm run dev